-- PUBLIC.GENERO definition

-- Drop table

-- DROP TABLE PUBLIC.GENERO;

CREATE TABLE Genero (
	idGenero INTEGER NOT NULL AUTO_INCREMENT,
	nombre CHARACTER VARYING(128) NOT NULL,
	CONSTRAINT GENERO_PK PRIMARY KEY (idGenero)
);
CREATE UNIQUE INDEX idGeneroPK ON PUBLIC.Genero (idGenero);


-- PUBLIC.PLATAFORMA definition

-- Drop table

-- DROP TABLE PUBLIC.PLATAFORMA;

CREATE TABLE PUBLIC.Plataforma (
	idPlataforma INTEGER NOT NULL AUTO_INCREMENT,
	nombre CHARACTER VARYING(128) NOT NULL,
	CONSTRAINT PLATAFORMA_PK PRIMARY KEY (idPlataforma)
);
CREATE UNIQUE INDEX idPlataformaPK ON PUBLIC.Plataforma (idPlataforma);


-- PUBLIC.JUEGO definition

-- Drop table

-- DROP TABLE PUBLIC.JUEGO;

CREATE TABLE PUBLIC.Juego (
	idJuego INTEGER NOT NULL,
	idGenero INTEGER NOT NULL,
	idPlataforma INTEGER NOT NULL,
	titulo CHARACTER VARYING(255) NOT NULL,
	miniatura CHARACTER VARYING(256),
	estado CHARACTER VARYING(64),
	descripcionCorta CHARACTER VARYING(512),
	descripcion CHARACTER VARYING(2000),
	url CHARACTER VARYING(256),
	editor CHARACTER VARYING(64),
	desarrollador CHARACTER VARYING(64),
	fecha DATE,
	CONSTRAINT JUEGO_PK PRIMARY KEY (idJuego),
	CONSTRAINT idGeneroFK FOREIGN KEY (idGenero) REFERENCES PUBLIC.Genero(idGenero) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT idPlataformaFK FOREIGN KEY (idPlataforma) REFERENCES PUBLIC.Plataforma(idPlataforma) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX idGeneroIdx ON PUBLIC.Juego (idGenero);
CREATE INDEX idPlataformaIdx ON PUBLIC.Juego (idPlataforma);
CREATE UNIQUE INDEX idJuego ON PUBLIC.Juego (idJuego);


CREATE TABLE PUBLIC.Imagen (
	idImagen INTEGER NOT NULL AUTO_INCREMENT,
	idJuego INTEGER NOT NULL,
	url CHARACTER VARYING(512) NOT NULL,
	imagen BLOB,
	CONSTRAINT idImagenPK PRIMARY KEY (idImagen),
	CONSTRAINT idJuegoFK FOREIGN KEY (idJuego) REFERENCES PUBLIC.Juego(idJuego) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX idImagenPKIdx ON PUBLIC.Imagen (idImagen);